// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type DeleteTask struct {
	TaskID string `json:"TaskID"`
}

type NewTask struct {
	TaskName string `json:"TaskName"`
	DueDate  string `json:"DueDate"`
}

type UpdateTask struct {
	TaskID   string `json:"TaskID"`
	TaskName string `json:"TaskName"`
	DueDate  string `json:"DueDate"`
	Status   bool   `json:"Status"`
}
