// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type DeleteTask struct {
	TaskID string `json:"taskID"`
}

type NewTask struct {
	TaskName string `json:"taskName"`
	DueDate  string `json:"dueDate"`
}

type UpdateTask struct {
	TaskID   string `json:"taskID"`
	TaskName string `json:"taskName"`
	DueDate  string `json:"dueDate"`
	Status   bool   `json:"status"`
}
