name: deploy to GitHub Pages

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  deployments:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - name: docker-compose up
        run: |
          docker-compose up -d
      
      - name: yarn install
        run: |
          docker-compose exec -T web yarn install

      - name: build nextjs
        run: |
          docker-compose exec -T web yarn build

      - name: export nextjs
        run: |
          docker-compose exec -T web yarn next export
    
      # https://qiita.com/manten120/items/87e9e822800403904dc8
      - name: add nojekyll
        run: touch ./out/.nojekyll

      - name: deploy
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./out
